// export const GET_DATA = "GET_DATA";
// export const ICON_INDEX = "ICON_INDEX ";
// export const LOADING = "LOADING ";
// export const REPLACE = "REPLACE ";
// export const ID_UPDATE = "ID_UPDATE ";
// export const DELETE = "DELETE ";
// export const UPDATE = "UPDATE ";
// export const INPUT_CHANGE = "INPUT_CHANGE ";
// export const USER_FIRST = "USER_FIRST ";
